version: 0.2

env:
  variables:
    REACT_APP_API_BASE: $REACT_APP_API_BASE 

phases:
  pre_build:
    commands:
      - printenv > .env
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build